### ISSUE TITLE
Compatibility with Windows 

### ISSUE THREAD

**Issue by skyprince999** [restackio/examples-python#49]
Hi 

Running the following command raises an exception

`poetry run services`

`AttributeError: module 'os' has no attribute 'uname'. Did you mean: 'name'?`

This is from the following lines 79 and 103 in `restack.py` where `os.uname()` has been used which is only compatible with [Unix systems ](https://bugs.python.org/issue008080)

Suggested alternative (_not sure if that solves the problem didnt run any tests!_)

`import platform`

and replace `os.uname().nodename` with `platform.uname().node`

OS: Windows 11

**Comment by aboutphilippe** [comment]
Thank you for reporting.
We addressed windows compatibility with https://github.com/restackio/examples-python/pull/50
